fix yaml files

diff --git a/.github/workflows/version-bump.yml b/.github/workflows/version-bump.yml
--- a/.github/workflows/version-bump.yml
+++ b/.github/workflows/version-bump.yml
@@ -26,6 +26,10 @@ jobs:
     runs-on: ubuntu-latest
     continue-on-error: false
     steps:
+      - name: Extract branch name
+        shell: bash
+        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
+        id: extract_branch
       - name: Checkout
         uses: actions/checkout@v4
         with:
@@ -35,37 +39,27 @@ jobs:
         with:
           node-version: '24'
           cache: 'npm'
-      - name: Cache dependencies
-        uses: actions/cache@v4
-        with:
-          path: |
-            node_modules
-            ~/.npm
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-
-      - name: Install dependencies
-        run: npm ci --ignore-scripts
+      - name: Fetch main branch
+        run: git fetch origin main:refs/remotes/origin/main
+      - name: Fetch feature branch
+        run: git fetch origin $GITHUB_HEAD_REF
       - name: Bump version
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
-
           # Get current version from PR branch
-          CURRENT_VERSION=$(node -p "require('./package.json').version")
+          CURRENT_VERSION=$(node -p "require('./package.json').version") || { echo "Failed to get version from package.json"; exit 1; }
           echo "Current version: $CURRENT_VERSION"
-
-          # Fetch main branch and get its version
-          git fetch origin main:main
-          MAIN_VERSION=$(git show main:package.json | jq -r .version)
+          # Get main version
+          MAIN_VERSION=$(git show origin/main:package.json | jq -r .version) || { echo "Failed to get version from package-main.json"; exit 1; }
           echo "Main version: $MAIN_VERSION"
-
           if [[ $(echo -e "$CURRENT_VERSION\n$MAIN_VERSION" | sort -V | head -n1) == "$CURRENT_VERSION" ]]; then
             echo "Bumping version as current version ($CURRENT_VERSION) is same or lower than main version ($MAIN_VERSION)"
+            git checkout $GITHUB_HEAD_REF
             npm run version:patch
             git add package.json package-lock.json
             git commit -m "chore: bump version [skip ci]"
-            git push origin ${{ github.ref_name }}
+            git push origin $GITHUB_HEAD_REF
           else
             echo "Skipping version bump as current version ($CURRENT_VERSION) is higher than main version ($MAIN_VERSION)"
           fi
